spring:
  application:
    name: library-events-producer
  profiles:
    active: local
  kafka:
    producer:
      properties:
        schema.registry.url: http://localhost:8081
        allow.auto.create.topics: false
      bootstrap-servers: localhost:9092
      group-id: library_group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    admin:
      properties:
        bootstrap.servers: localhost:9092

topic:
  library: avro-library-tp